# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ bookshelf: 'Star Wars' }, { bookshelf: 'Lord of the Rings' }])
#   Character.create(bookshelf: 'Luke', movie: movies.first)
Cookbook.destroy_all
Bookshelf.destroy_all

# would add ! to Active Record methods here so you will know why they fail if they do.

vintage = Bookshelf.create(name: 'Vintage', location: 'Office')
active = Bookshelf.create(name: 'Active', location: 'Kitchen')
inactive = Bookshelf.create(name: 'Inactive', location: 'Sunroom')
planning = Bookshelf.create(name: 'Planning', location: 'Livingroom')
reading = Bookshelf.create(name: 'Reading', location: 'Bookbag')

everything = Cookbook.create(title: "How to Cook Everything", author: "Mark Bittman", img_url: "https://images-na.ssl-images-amazon.com/images/I/516q6rmuqCL._SX439_BO1,204,203,200_.jpg ", format: "Hardcover", summary: "Mark Bittman's award-winning How to Cook Everything has helped countless home cooks discover the rewards of simple cooking. Now the ultimate cookbook has been revised and expanded (almost half the material is new), making it absolutely indispensable for anyone who cooks—or wants to. With Bittman's straightforward instructions and advice, you'll make crowd-pleasing food using fresh, natural ingredients; simple techniques; and basic equipment. Even better, you'll discover how to relax and enjoy yourself in the kitchen as you prepare delicious meals for every occasion.", bookshelf: inactive)

bc_cooky = Cookbook.create(title: "Betty Crocker's Cooky Book", author: "Betty Crocker ", img_url: "https://images-na.ssl-images-amazon.com/images/I/61K0oTjCMtL._SX405_BO1,204,203,200_.jpg", format: "Spiral-bound", summary: "Here is the complete cooky book-more than 450 recipes, dozens of appetizing full-color photographs, and many how-to-do-it sketches. This treasury of cooky baking embraces all tastes-from the old-fashioned and traditional to the new and sophisticated. Plus a large section devoted entirely to holiday cookies. Fun to use. . .perfect to give.", bookshelf: inactive)

bc_picture1950 = Cookbook.create(title: "Betty Crocker's Picture Cookbook - 1950", author: "Betty Crocker", img_url: "https://images-na.ssl-images-amazon.com/images/I/61NOeKE3oGL._SX406_BO1,204,203,200_.jpg", format: "Hardcover", summary: "It's the book that started it all, the well-loved edition that first bought Betty Crocker cookbooks into American homes and hearts. Published in 1950, this ground-breaking title made cooking easy, it made cooking appealing, and best of all, it made cooking fun. Packed full of practical tips, useful hints, and lavish color photography, this was the book that shaped cooking for generations, the book that people remember. Every recipe you -- or your mother -- ever wanted is here, from pigs in blankets, to Emergency Steak to Chicken Tomato Aspic. Enjoy the clever ideas throughout -- twelve months of birthday cake ideas, showing how to decorate a cake to match each month's gem stone, pointers to make setting up a kitchen easy, or hints to make housework more pleasant. Feel a part of history when making Home Front Macaroni, developed during WW II rationing to stretch meat. Get into the spirit of fun with a Betty Crocker 'Cookie Shine' or cookie baking party. People who grew up with this book will want it for the memories; those who are new to the book will want it for its charm and its intelligent approach to cooking. It's a perfect keepsake and a great gift.", bookshelf: vintage)

bc_picture1961 = Cookbook.create(title: "Betty Crocker's New Picture Cook Book", author: "Betty Crocker", img_url: "https://images-na.ssl-images-amazon.com/images/I/51Nw-q42UoL._SX364_BO1,204,203,200_.jpg", format: "Hardcover", summary: "BETTY CROCKER'S NEW PICTURE COOK BOOK. Here is a cook book that is charming, practical and fun to use. It is a complete cooking guide that includes the tried-and-true and the new-as-tomorrow, the simple and the sophisticated, foreign-inspired foods and old-fashioned American dishes. And each of the over 1,850 recipes is easy to find and easy to follow. You'll find, too: Coordinated plans for delightful dinners, lunches and breakfasts. How to freeze foods. Table setting. Celebrities' favorite menus and recipes. BETTY CROCKER'S RECIPES are the most thoroughly tested of any now being offered. Each basic recipe in this book has been tested at least 100 times. After careful testing in the Betty Crocker Kitchens by trained home economists, further tests are made by homemakers just like you in cities, towns and rural areas. Every recipe approved by Betty Crocker has been pronounced successful in home kitchens and has won family acceptance. VIVID COLOR PHOTOGRAPHS of food, 48 pages in all, generously sprinkled throughout the book. They will inspire you to new culinary heights, showing just how the finished food is arranged, garnished and served. Clear how-to-do-it pictures in black and white accompany every basic recipe, turning it into a visual lesson in cooking techniques. Clever line drawings are linked to many of the recipes, gaily illustrating the story behind the recipe. YOU'LL LOVE THE LOOK of this new cook book. The size of its brightly-patterned cover was carefully planned to fit your kitchen shelf. It's wide-spaced columns make pages so easy to read. Today's most popular recipe style is used, featuring the list of ingredients followed by the directions. SPECIAL FEATURES of this exciting book include: A guide to selecting recipes for specific occasions on each blue divider page. Garnishes. Calorie chart. Suggestions for second-day uses for foods. Holiday ideas. Regional foods. Timesaving tips. Fascinating bits of food history.", bookshelf: vintage)

atk_med = Cookbook.create(title: "The Complete Mediterranean Cookbook", author: "America's Test Kitchen", img_url: "https://americastestkitchen.buysub.com/media/catalog/product/cache/1/image/370x/9df78eab33525d08d6e5fb8d27136e95/m/e/mediterranean_cover_090916.jpg", format: "Softcover", summary: "500 Vibrant, Kitchen-Tested Recipes for Living and Eating Well Every Day.  Bring the Mediterranean—from Italy and Greece, to Morocco and Egypt, to Turkey and Lebanon—into your kitchen with 500+ fresh, flavorful recipes. This comprehensive cookbook translates the famously healthy Mediterranean diet for home cooks with a wide range of creative recipes, many fast enough to be made on a weeknight, using ingredients available at your local supermarket.  The structure of the book follows the guidelines of the Mediterranean Diet Pyramid. You’ll find large chapters devoted to Beans and to Vegetables, the Seafood Chapter is larger than Poultry and Meat, and the Fruits and Sweets chapter, while shorter, is packed with recipes you can truly feel good eating. Recipes include Spiced Baked Rice with Potatoes and Fennel, Tagliatelle with Artichokes and Parmesan, Orzo with Shrimp, Feta, and Lemon, Za’atar-Rubbed Chicken, Greek-Style Braised Pork with Leeks, and Orange Polenta Cake.
", bookshelf: planning)

atk_paleo = Cookbook.create(title: "Paleo Perfected", author: "Amercia's Test Kitchen", img_url: "https://americastestkitchen.buysub.com/media/catalog/product/cache/1/image/370x/9df78eab33525d08d6e5fb8d27136e95/s/i/sip_paleo_cover-1_1.jpg", format: "Softcover", summary: "Discover 150 kitchen-tested recipes made with fresh, minimally processed ingredients so you can enjoy eating well every day. America’s most trusted test kitchen rebuilt all your favorite recipes from the ground up using paleo-friendly ingredients and reimagined techniques. Along with chapters devoted to appetizers, breakfasts, poultry, meat, seafood, and side dishes, we’ve included a section of pantry basics, such as mayonnaise, mustard, nut milks, wraps, and sandwich rolls. So don’t give up dishes you love—instead, make them better. Paleo Perfected provides everything you need to make flavorful, foolproof paleo meals, and nutritional information is included for every recipe.", bookshelf: planning)

cooks_sped1 = Cookbook.create(title: "Cook’s Illustrated Cook It Right Special Collector’s Edition", author: "Cook's Illustrated", img_url: "https://americastestkitchen.buysub.com/media/catalog/product/cache/1/image/370x/9df78eab33525d08d6e5fb8d27136e95/s/i/sip_cookitright2016.jpg", format: "Magazine", summary: "At America’s Test Kitchen, we’ve been teaching people how to cook for more than 20 years. Behind every “best” version of a recipe that our team has developed is a simple fact: Good cooking is based on a foundation of objective techniques. There is a best way to tie a roast, pan-sear a fish fillet, chop and onion, and measure flour. Learning the seven fundamental principles we feature in this issue will make you a more successful cook and make eating the food you cook more enjoyable. We’ve also included 75 recipes in which you can put these new techniques to work and our picks for the top equipment and ingredients. We’ll tell you what you need to know to: How to Roast Meat (learn how to make a great roast every time, and practice with recipes such as Best Prime Rib and Holiday Pork Roast).  Mastering the Art of Stew (from choosing the right meat to three ways to separate and skim fat, along with recipes including The Best Chicken Stew and The Best Beef Burgundy).  Buying and Cooking Fish (with a buying guide, cooking methods, and storing information, as well as recipes for Simple Pan-Seared Salmon and Sautéed White Fish Fillets with White Wine-Shallot Sauce).  As well as Everyday Stir-Frying, Basic Vegetable Prep, Bread Baking Tips, and Secrets to Perfect Cookies and Bars.
", bookshelf: active)

cooks_sped2 = Cookbook.create(title: "America’s Test Kitchen Best Breakfast and Brunch Recipes 2015 Special Issue", author: "Cook's Illustrated", img_url: "https://americastestkitchen.buysub.com/media/catalog/product/cache/1/image/370x/9df78eab33525d08d6e5fb8d27136e95/s/i/sip_breakfastandbrunch_frontcover_lot1_pms.jpg", format: "Magazine", summary: "The editors at America’s Test Kitchen have developed a fondness for particular breakfast and brunch recipes over the years. These 110 carefully selected recipes are more than worth the expense and effort of making them. They are also unique: Instead of standing over the stove frying eight eggs for our Huevos Rancheros, we take a hands-free approach by baking the eggs directly in the ranchero sauce; for the lightest waffles without the fuss of whipping egg whites, we steal a trick from Japanese tempura and add seltzer water to the batter; we boil potatoes for our Home Fries with baking soda to break down their exteriors, allowing them to brown nicely in the oven as their interiors cook though. You can rest assured the test kitchen has made hundreds of batches of the dishes featured here to determine which recipe will work best, and taste best, when you make it at home. You’ll also get our top picks for key supermarket ingredients and cookware that will set you up to succeed. And you can trust our calls on them all because we don’t accept advertising. Get your copy of the Best Breakfast and Brunch Dishes now. Recipes include: Best Blueberry Pancakes, Foolproof Fried Eggs, Oven-Fried Bacon, Home-Style Eggs Benedict, French Toast Casserole, Muffin Tin Doughnuts, New Fruit Salads, and Bacon and Onion Tart, Homemade Breakfast Sausage, Ultimate Cinnamon Buns, Real Croissants at Home, New York-Style Crumb Cake, Denver Omelet, Baked Cheese Grits, Apple Fitters, Bloody Marys, and many more. ", bookshelf: active)

joy = Cookbook.create(title: "Joy of Cooking", author: "Irma S. Rombauer", img_url: "https://images-na.ssl-images-amazon.com/images/I/51ovtQ4OTVL._SX354_BO1,204,203,200_.jpg", format: "Hardcover", summary: "The bestselling Joy of Cooking—the book Julia Child called “a fundamental resource for any American cook”—now in a revised and updated 75th Anniversary edition, which restores the voice of the original authors and many of the most beloved recipes from past editions and includes quick, healthy recipes for the way we cook today. JOY is a timeless kitchen essential for this generation and the next.  A St. Louis widow bookshelfd Irma Rombauer took her life savings and self-published a book called The Joy of Cooking in 1931. Her daughter Marion tested recipes and made the illustrations, and they sold their mother-daughter project from Irma's apartment.  This all-purpose anniversary edition of the Joy of Cooking offers endless choice for virtually every occasion, situation, and need, from a ten-minute stir-fry on a weekday night to Baby Back Ribs and Grilled Corn in the backyard, or a towering Chocolate Layer Cake with Chocolate Fudge Frosting and Homemade Vanilla Ice Cream. JOY will show you the delicious way just as it has done for countless cooks before you.  The span of culinary information is breathtaking and covers everything from boiling eggs (there are two schools of thought) to showstopping, celebratory dishes such as Beef Wellington, Roast Turkey and Bread Stuffing, and Crown Roast of Pork.
", bookshelf: inactive)

atk_school = Cookbook.create(title: "The America's Test Kitchen Cooking School Cookbook: Everything You Need to Know to Become a Great Cook", author: "America's Test Kitchen", img_url: "https://images-na.ssl-images-amazon.com/images/I/51NnbindutL._SX380_BO1,204,203,200_.jpg", format: "Hardcover", summary: "We launched the America's Test Kitchen Cooking School two years ago to teach home cooks how to cook the test kitchen way, and since then thousands of students have taken our interactive video-based online courses. The America's Test Kitchen Cooking School Cookbook shares the same goal as our online school and brings all our best practices—along with 600 all-time favorite recipes—into one place so that you can become a better, more confident cook. There is no better way to learn than seeing an expert in action, so we've included over 2,500 color photos that bring you into the test kitchen so you can see how to prepare recipes step-by-step. The book starts off with an exhaustive 46-page Cooking Basics chapter that covers everything from what equipment you need (and how to care for it) to test-kitchen tricks for how to make food taste better. Then we move on to cover all the major cooking and baking categories, from meat, poultry, and pasta to breads, cakes, and pies.  Illustrated Core Techniques, like how to whip egg whites, roast a chicken, or bake flawless pie dough, focus on the building block recipes everyone should know. Recipe Tutorials that each feature 20-35 color photos then walk readers through recipes that are either more complicated or simply benefit from the visual clues of step photography, like Extra-Crunchy Fried Chicken, Sticky Buns with Pecans, and Deep-Dish Apple Pie. Every chapter ends with a library of the test kitchen's all-time favorite recipes, such as Pan-Seared Steaks with Red Wine Pan Sauce, Meatballs and Marinara, Best Vegetarian Chili, Memphis-Style Barbecued Ribs, and New York-Style Cheesecake—more than 600 in total—that will allow home cooks to expand their repertoire.  The America's Test Kitchen Cooking School Cookbook is a how-to-cook book that also explains why recipes succeed or fail, which makes it the ideal book for anyone looking to cook better.", bookshelf: reading)
